//
try {
    throw new Exception("Oh no!");
} catch (Exception error) {
    System.out.println("Found an error.");
} finally {
    // ...
}
//
